mindmap
  root((Mermaid))
    Origins
      Long history
      Tony Buzan popularised
    Diagram types
      Flow
        Flowchart
        Git Graph
      UML
        Sequence
        Class
        State
      Data
        Pie
        XY Chart
        Sankey
      Project
        Gantt
        Journey
    Use cases
      Documentation
      Brainstorming
      Planning
      Education
